name: Robô Vigia da Barbearia
on:
  schedule:
    - cron: "*/20 * * * *" # Roda a cada 20 minutos
  workflow_dispatch: # Permite rodar manualmente pra testar

jobs:
  acordar_site:
    runs-on: ubuntu-latest
    steps:
      - name: Bater na porta (Ignorando erros)
        run: |
          # O comando curl -I apenas pede o cabeçalho do site
          # O flag --max-time 10 evita que ele fique preso se o site demorar
          # O flag || true garante que o GitHub sempre dê "Sucesso" (verde), mesmo se o site der erro 303
          curl -I --max-time 10 -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://barbeariavasques.streamlit.app/ || true
          echo "Bati na porta. O site deve ter acordado."
